name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Checkout Unity repo
      uses: actions/checkout@v4
      with:
        repository: ThrowTheSwitch/Unity.git
        path: tools
        ref: Master
    - name: Navigate to project directory
      run: cd path/to/your/project
    - name: Make and run
      run: make clean; make -j4
