name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-run:
  
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
    uses: actions/checkout@v4
    with:
      path: main
    - name: Checkout Unity repo
    uses: actions/checkout@v4
    with:
      repository: ThrowTheSwitch/Unity.git
      path: tools
    - name: make
      run: make -j4
